/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package com.atobe.lpr.controller;

import com.atobe.lpr.controller.request.ReviewRequest;
import com.atobe.lpr.domain.Review;
import com.atobe.lpr.domain.ReviewStatus;
import com.atobe.lpr.dto.ReviewResultDTO;
import com.atobe.lpr.service.ReviewService;
import java.util.List;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@Slf4j
@RestController
@RequestMapping("/reviews")
public class ReviewsController {
  @Autowired ReviewService reviewService;

  @GetMapping
  @ResponseBody
  List<Review> getImageReviewByStatus(@RequestParam ReviewStatus reviewStatus) {
    return reviewService.findByReviewStatus(reviewStatus);
  }

  @GetMapping("/{reviewId}")
  @ResponseBody
  Review getPhotoReviewById(@PathVariable("reviewId") Long reviewId) {
    return reviewService.findById(reviewId);
  }

  @PatchMapping("/{reviewId}")
  @ResponseBody
  Review reviewPhoto(@PathVariable("reviewId") Long reviewId) {
    return reviewService.reviewPhoto(reviewId);
  }

  @PostMapping("/{reviewId}")
  @ResponseBody
  Review submitReview(
      @PathVariable("reviewId") Long reviewId, @RequestBody ReviewRequest reviewRequest) {
    ReviewResultDTO reviewResultDTO =
        ReviewResultDTO.builder()
            .reviewId(reviewId)
            .licensePlateNumber(reviewRequest.getLicensePlateNumber())
            .build();
    return reviewService.submitReview(reviewResultDTO);
  }
}
