/*
 * License Plate Review (LPR) API
 * License Plate Review (LPR) API is a module of a tolling BackOffice system, responsible for allowing authorized users reviewing photos of vehicles which were not successfuly recognized in terms of the license plate number. In order to simplify a development only a small set of operations is described below. The system receives photos in asyncronous way by means of a message broker.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.atobe.lpr.domain;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
@ToString
@Entity
@Table
public class Photo implements Serializable {

  @Id private Long photoId;

  private String fileName;

  private String filePath;

  public Long getPhotoId() {
    return this.photoId;
  }

  public String getFileName() {
    return this.fileName;
  }

  public String getFilePath() {
    return this.filePath;
  }

  public void setPhotoId(Long photoId) {
    this.photoId = photoId;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public void setFilePath(String filePath) {
    this.filePath = filePath;
  }
}
