/*
 * License Plate Review (LPR) API
 * License Plate Review (LPR) API is a module of a tolling BackOffice system, responsible for allowing authorized users reviewing photos of vehicles which were not successfuly recognized in terms of the license plate number. In order to simplify a development only a small set of operations is described below. The system receives photos in asyncronous way by means of a message broker.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.atobe.lpr.domain;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
@Data
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
@ToString
@Entity
@Table
public class Review implements Serializable {
  @Id private Long reviewId;

  @OneToOne
  @JoinColumn(name = "PHOTO_ID")
  private Photo photo;

  private String licensePlateNumber;

  @Enumerated(EnumType.STRING)
  private ReviewStatus reviewStatus;

  public Review(Photo photo) {
    this.photo = photo;
    this.reviewId = photo.getPhotoId();
    this.reviewStatus = ReviewStatus.CREATED;
  }

  public Long getReviewId() {
    return this.reviewId;
  }

  public Photo getPhoto() {
    return this.photo;
  }

  public String getLicensePlateNumber() {
    return this.licensePlateNumber;
  }

  public ReviewStatus getReviewStatus() {
    return this.reviewStatus;
  }

  public void setReviewId(Long reviewId) {
    this.reviewId = reviewId;
  }

  public void setPhoto(Photo photo) {
    this.photo = photo;
  }

  public void setLicensePlateNumber(String licensePlateNumber) {
    this.licensePlateNumber = licensePlateNumber;
  }

  public void setReviewStatus(ReviewStatus reviewStatus) {
    this.reviewStatus = reviewStatus;
  }
}
